import './globals.css';
import Link from 'next/link';



export const metadata = {
  title: 'Nam Fam',
  description: 'Showcasing my work and skills.',
};

import ChatPopup from './components/ChatPopup';

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-white flex flex-col h-screen">
      
        <header className="bg-white-600 p-1 text-black">
          <nav className="container flex flex-col md:flex-row justify-center mx-auto font-semibold">
            {/* <h1 className="text-2xl font-bold mb-4 md:mb-0">My Portfolio</h1> */}
            <div>
              <Link href="/" className="px-4 py-2 inline-block text-black hover:text-yellow-400">Home</Link>
              <Link href="/about" className="px-4 py-2 inline-block text-black hover:text-yellow-400">About</Link>
              <Link href="/projects" className="px-4 py-2 inline-block text-black hover:text-yellow-400">Projects</Link>
              <Link href="/contact" className="px-4 py-2 inline-block text-black hover:text-yellow-400">Contact</Link>
            </div>
          </nav>
        </header>

        <main className="flex-grow flex flex-col w-full mx-auto md:flex-row h-full overflow-hidden">
          <section className="flex-1 p-0">
            {children}
          </section>
          
          {/* <aside className="hidden md:block p-4"> */}
            {/* Include ChatInterface only on the Home page */}
            {/* You can use conditional rendering or a layout-based approach here */}
          {/* </aside> */}
        </main>

        <footer className="bg-white-600 p-1 text-black justify-center text-center">
          &copy; {new Date().getFullYear()} NamFam
        </footer>

        <ChatPopup /> 
      </body>
    </html>
  );
}



// export const metadata = {
//   title: 'My Portfolio',
//   description: 'Showcasing my work and skills.',
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>
//         <header className="bg-blue-600 p-4 text-white">
//           <nav className="container mx-auto flex flex-col md:flex-row justify-between">
//             <h1 className="text-2xl font-bold mb-4 md:mb-0">My Portfolio</h1>
//             <div>
//               <a href="#education" className="px-4 py-2 inline-block text-white hover:text-yellow-400">Education</a>
//               <a href="#experience" className="px-4 py-2 inline-block text-white hover:text-yellow-400">Experience</a>
//               <a href="#projects" className="px-4 py-2 inline-block text-white hover:text-yellow-400">Projects</a>
//               <a href="#awards" className="px-4 py-2 inline-block text-white hover:text-yellow-400">Awards</a>
//               <a href="#skills" className="px-4 py-2 inline-block text-white hover:text-yellow-400">Skills</a>
//             </div>
//           </nav>
//         </header>
//         <main className="container mx-auto p-4">{children}</main>
//         <footer className="bg-blue-600 p-4 text-white text-center">
//           &copy; {new Date().getFullYear()} My Portfolio
//         </footer>
//       </body>
//     </html>
//   );
// }



// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }

// import Link from 'next/link';

// const Layout = ({ children }) => {
//   return (
//     <div className="min-h-screen bg-gray-100">
//       <header className="bg-blue-600 p-4 text-white">
//         <nav className="container mx-auto flex flex-col md:flex-row justify-between">
//           <h1 className="text-2xl font-bold mb-4 md:mb-0">My Portfolio</h1>
//           <div>
//             <Link href="#education" className="px-4 py-2 inline-block text-white hover:text-yellow-400">Education</Link>
//             <Link href="#experience" className="px-4 py-2 inline-block text-white hover:text-yellow-400">Experience</Link>
//             <Link href="#projects" className="px-4 py-2 inline-block text-white hover:text-yellow-400">Projects</Link>
//             <Link href="#awards" className="px-4 py-2 inline-block text-white hover:text-yellow-400">Awards</Link>
//             <Link href="#skills" className="px-4 py-2 inline-block text-white hover:text-yellow-400">Skills</Link>
//           </div>
//         </nav>
//       </header>
//       <main className="container mx-auto p-4">{children}</main>
//       <footer className="bg-blue-600 p-4 text-white text-center">
//         &copy; {new Date().getFullYear()} My Portfolio
//       </footer>
//     </div>
//   );
// };

// export default Layout;
